#!/usr/bin/env ruby

# How plugin, to make up for the fact the Sow clobber's
# Hoe's +sow+ command. Isn't it a bit silly to have a
# command called +sow+ when it could just as well be
# called +hoe+ anyway?

setup do |*arguments|
  abort_unless_empty_or_managed
  metadata.name = arguments.shift || destination.basename.to_s
  #abort "Project name argument required." unless metadata.name
end

scaffold do
  copy "**/*" #, '.'
end

