#!/usr/bin/env ruby

# TODO: Perhaps add automatic detection of location of features?

name = arguments.shift

abort "feature name is required" unless name

metadata.feature = name

directory = arguments.shift || 'features'

scaffold do
  copy "__feature__.feature", directory
end

