.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SOW\-GEMDO" "1" "October 2010" "RubyWorks" ""
.
.SH "NAME"
\fBsow\-gemdo\fR \- create GEM DO POM metadata files
.
.SH "SYNOPSIS"
\fBsow gemdo <name>\fR \fBsow gemdo <name> top=true\fR
.
.SH "DESCRIPTION"
This seed creates GEM DO POM metadata files\. By default, or selecting the \fBmeta\fR type, the files generated are:
.
.P
meta/data\.rb meta/package meta/profile
.
.P
If the \fBtop\fR selection is made the files are:
.
.P
PROFILE VERSION
.
.P
The default is highly recommeded\.
.
.SH "NAME"
The name argument is used to fill in some of the metadata fields\. Other fields are filed in via common environment variables if they exist\. Is with all Sow templates, if a field is not found an \fB___<name>___\fR entry is used to make it easier to find and edit unfinished files\.
.
.SH "COPYRIGHT"
Copyright (c) 2010 Thamas Sawyer
.
.SH "SEE ALSO"
sow(1)
