.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SOW\-LICENSE" "1" "October 2010" "RubyWorks" ""
.
.SH "NAME"
\fBsow\-license\fR \- provide a license file
.
.SH "SYNOPSIS"
\fBsow license <name>\fR
.
.SH "DESCRIPTION"
Add a specified license to your project\. Usually the file created is called \fBLICENSE\fR\. But the \fBgpl\fR license uses \fBCOPYING\fR instead\. The \fBapache\fR license also provides a \fBNOTICE\fR file\.
.
.P
Available licenses inclide \fBmit\fR, \fBlgpl\fR, \fBbsd\fR, and so on\.
.
.P
If no license name is given, a list of available licenses will be shown\.
.
.SH "COPYRIGHT"
Copyright (c) Thomas Sawyer 2010
.
.SH "SEE ALSO"
sow(1)
