.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SOW\-BASIC\-RUBY" "1" "October 2010" "RubyWorks" ""
.
.SH "NAME"
\fBsow\-basic\-ruby\fR \- create a basic Ruby project layout
.
.SH "SYNOPSIS"
\fBsow basic\.ruby <name>\fR
.
.SH "DESCRIPTION"
Traditional Ruby project scaffolding\. This provides the common structure for a standard Ruby project\. This seed takes a single argument for the project\'s name\. The name must a single alphanumeric word \-\-what is often called a "unixname"\. If the name is not given the basename of the destination directory will be used\.
.
.SH "COPYRIGHT"
Copyright (c) 2010 Thomas Sawyer
.
.SH "SEE ALSO"
sow(1)
