.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SOW\-CUCUMBER" "1" "October 2010" "RubyWorks" ""
.
.SH "NAME"
\fBsow\-cucumber\fR \- create a cucumber feature
.
.SH "SYNOPSIS"
`sow cucumber \fIname\fR [directory]
.
.SH "DESCRIPTION"
Create a new cucumber feature file\. If the project is not yet setup for Cucumber then basic setup files will be provided in addition to the feature file\.
.
.SH "ARGUMENTS"
The cucuumber seed takes two arguments\.
.
.IP "\(bu" 4
\fBfeature\fR: The name of the new feature (required)\.
.
.IP "\(bu" 4
\fBdirectory\fR The features directory (default \fBfeatures/\fR)\.
.
.IP "" 0
.
.P
If you are using a non\-standard location for features, always be sure to provide it as the second argument\.
.
.SH "COPYRIGHT"
Copyright (c) 2010 Thomas Sawyer
.
.SH "SEE ALSO"
sow(1)
