#!/usr/bin/env ruby

# Add specified license to your project.

LICENSES = %w[gpl lgpl mit]

setup do |licence, *_|
  lic = (license || 'mit').downcase
  unless LICENSES.include?(lic)
    abort "Unrecognized license name. Choose:\n  " + LICENSES.join("\n  ")
  end
  metadata.license = lic.upcase
end

scaffold do
  copy "*", '.', :cd => license.downcase
end

