#!/usr/bin/env ruby

# Add a specified license to your project.
#
#   sow license <name>
# 
# If no license name is given a list of available license it printed.

licenses = %w{apache gpl lpgl mit ruby}

argument :license

if data.license && (seed.path + data.license).directory?
  copy '*', :from=>data.license
else
  abort "License not found. Try:\n  " + licenses.join("\n  ")
end

