#!/usr/bin/env ruby

utilize 'pom'

name = arguments.first || metadata['name'] #|| destination.basename.to_s

abort "Name is required."         unless name
abort "Name must be single word." unless name =~ /\w+/

metadata.name    = name
metadata.title   = metadata['title']   || name.capitalize
metadata.contact = metadata['contact'] || metadata['EMAIL']

#
scaffold do
  copy("PROFILE")
  copy("VERSION")
  copy("REQUIRE") unless File.exist?('Gemfile') #destination.glob('Gemfile').first #include?
end

