#!/usr/bin/env ruby

utilize 'pom'

setup do |*args|
  name = args.first || metadata['name'] || destination.basename.to_s

  abort "Name is required."         unless name
  abort "Name must be single word." unless name =~ /\w+/

  metadata.name  = name
  metadata.title = metadata['title'] || name.capitalize

  if destination.exist?
    files = Dir.entries(destination) - ['.', '..', 'PROFILE', 'VERSION']
    if !files.empty? and !managed?
      abort "The ruby scaffold is intended for new projects.\n" +
            "But this destination directory is not empty.\n" +
            "Please use the --force, --skip or --prompt to proceed."
    end
  end

  #if destination.glob('PROFILE').first
  #  profile = YAML.load(File.new('PROFILE'))
  #  metadata << profile
  #end

  #if destination.glob('VERSION').first
  #  version = YAML.load(File.new('VERSION'))
  #  metadata << version
  #end
end

scaffold do
  copy("**/*") #, :omit => "meta")
  copy("bin/*", :chmod=>0744)
  copy("README.rdoc.till", :verbatim => true)
end

