#!/usr/bin/env ruby

setup do |*arguments|
  metadata.directory = arguments.shift || 'features'
  metadata.feature   = arguments.shift || 'your_first'
end

scaffold do
  copy "**/*", metadata.directory.chomp('/') + '/'
end

