#!/usr/bin/env ruby

LICENSES = %w[gpl lgpl mit apache]

argument :license  #, :default => 'mit'

lic = (metadata.license || 'mit').downcase
unless LICENSES.include?(lic)
  raise "Unrecognized license name. Choose:\n  " + LICENSES.join("\n  ")
end
metadata.license = lic.upcase

scaffold do
  copy "#{lic}//*", '.'
end

