#!/usr/bin/env ruby

#  This seed creates GEM DO POM metadata files:
#
#   meta/data.rb
#   meta/package
#   meta/profile
#
utilize 'gemdo'

argument :name

name = metadata.name

#name = arguments.first || metadata['name'] #|| destination.basename.to_s

abort "Name is required."         unless name
abort "Name must be single word." unless name =~ /\w+/

metadata.title   = metadata['title']   || name.capitalize
metadata.contact = metadata['contact'] || metadata['email']

scaffold do
  copy("**/*", :render=>'erb')
end

