#!/usr/bin/env ruby

utilize 'pom'

ensure_empty('PROFILE', 'VERSION')

#argument :name, :default => destname
metadata.name = arguments.shift || metadata.name || destname

raise "Name is required."         unless metadata.name
raise "Name must be single word." unless metadata.name =~ /\w+/

#metadata.name    = name  # TODO
metadata.title   = metadata.title   || metadata.name.capitalize
metadata.contact = metadata.contact || metadata['EMAIL']

# TODO: Do not overwrite PROFILE, VERSION or REQUIRE if they exist
scaffold do
  copy("**/*")
  copy("bin/*", 0744)
  #skip('PROFILE', 'VERSION', 'REQUIRE')
end

