.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SOW\-NEW" "1" "October 2010" "RubyWorks" ""
.
.SH "NAME"
\fBsow\-new\fR \- germinate a new seed
.
.SH "SYNOPSIS"
\fBsow new\fR \fIpath\fR \fIname\fR [\fIargs\fR\.\.\.]
.
.SH "DESCRIPTION"
Germinate a new seed\.
.
.SH "OPTIONS"
These options control whether output is written to file(s)\.
.
.TP
\fB\-f\fR, \fB\-\-force\fR
Force overwrites of any destination files that already exist\.

