--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Sow configuration.
full_name: Sow::Session#config
is_singleton: false
name: config
params: ()
visibility: public
